name: Add New Org Issues to Project

on:
  issues:
    types: [opened]

env:
  PROJECT_URL: "https://github.com/orgs/tlon-team/projects/9"
  PROJECT_NUMBER: "9" # Corresponds to project 9

# Permissions for the GITHUB_TOKEN used by the workflow runner itself
permissions:
  issues: read # Required to access issue details like github.event.issue.html_url from the event payload.
               # Project write permissions will be provided by the PAT (ORG_PAT_PROJECTS) below.

jobs:
  add_issue_to_project:
    name: Add issue to Tlon Org Project
    if: github.repository_owner == 'tlon-team'
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI (ensures it's available)
        run: |
          type -p gh >/dev/null || (type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y) && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null && sudo apt update && sudo apt install gh -y)
          echo "GH CLI Version:"
          gh --version

      - name: Add newly created issue to project
        env:
          # Using a PAT stored as an organization secret is recommended for org projects.
          # Ensure the secret ORG_PAT_PROJECTS exists in your tlon-team organization settings
          # and the PAT has 'repo' (or 'public_repo') and 'project' scopes.
          GH_TOKEN: ${{ secrets.ORG_PAT_PROJECTS }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          echo "Processing issue: $ISSUE_URL"
          echo "Adding to project (URL): ${{ env.PROJECT_URL }}"
          echo "Project Number: ${{ env.PROJECT_NUMBER }}"

          gh project item-add "${{ env.PROJECT_NUMBER }}" --owner "tlon-team" --url "$ISSUE_URL"

          echo "Issue successfully added to project."
