name: Add New Org Issues to Project

# Trigger when an issue is opened in any repository within the organization
on:
  issues:
    types: [opened]

# Environment variables accessible in all jobs
env:
  PROJECT_URL: "https://github.com/orgs/tlon-team/projects/9"
  ORGANIZATION_NAME: "tlon-team" # Your organization's name

# Permissions for the GITHUB_TOKEN
# The GITHUB_TOKEN needs permission to read issue data and write to organization projects.
permissions:
  issues: read    # To access github.event.issue.node_id
  # projects: write # To add items to the project

jobs:
  add_issue_to_project:
    if: github.repository_owner == 'tlon-team'
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI (ensures it's available)
        run: |
          # Your existing gh install script
          type -p gh >/dev/null || (type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y) && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null && sudo apt update && sudo apt install gh -y)
          echo "GH CLI Version:"
          gh --version

      - name: Add newly created issue to project
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          # PROJECT_URL: ${{ env.PROJECT_URL }} # Still available if needed for echo
          PROJECT_NUMBER: "9" # Explicitly define project number
        run: |
          echo "Processing issue: $ISSUE_URL"
          echo "Adding to project (URL): ${{ env.PROJECT_URL }}" # Use the original env.PROJECT_URL for logging
          echo "Project Number: $PROJECT_NUMBER"

          # Use the project number as the first argument
          gh project item-add "$PROJECT_NUMBER" --owner "tlon-team" --url "$ISSUE_URL"

          echo "Issue successfully added to project."
